function DirtLevels1 = importDirtRecord(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DIRTLEVELS1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  DIRTLEVELS1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  DirtLevels1 = importfile("/Users/user/Library/CloudStorage/OneDrive-TheUniversityofManchester/Manchester/Responsibility/DirtExperiment/Naive/Result/Dirt200/DirtLevels_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Mar-2023 09:10:06

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["remainingTime", "dirtLevel", "badDirtLevel"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DirtLevels1 = readtable(filename, opts);

%% Convert to output type
DirtLevels1 = table2array(DirtLevels1);
end