function AliveTime1 = importAliveFile(filename,runNumber,dirtAppearenceRate)
%IMPORTFILE Import data from a text file
%  ALIVETIME1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  ALIVETIME1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  AliveTime1 = importfile("/Users/user/Library/CloudStorage/OneDrive-TheUniversityofManchester/Manchester/Responsibility/DirtExperiment/Naive/Result/Dirt200/AliveTime_1.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Mar-2023 09:30:16

%% Input handling

% If dataLines is not specified, define defaults
dataLines = [2, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["badDirt", "timeAlive"];
opts.VariableTypes = ["categorical", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "badDirt", "EmptyFieldRule", "auto");

% Import the data
AliveTime = readtable(filename, opts);

[GN, ~, G] = unique(AliveTime.badDirt);

AliveTime1 = zeros(size(G,1),4);
AliveTime1(:,4) = table2array(AliveTime(:,2));
AliveTime1(:,3) = G;
AliveTime1(:,2) = dirtAppearenceRate;
AliveTime1(:,1) = runNumber;

end